### ISSUE TITLE
Coordinates for detected objects

### ISSUE THREAD

**Issue by sohartma** [cagbal/cob_people_object_detection_tensorflow#51]
First of all, Thank you for this package.

I want to make my robot follow a detected object. I've trained my own model for detecting only balls. And i need the x and y coordinates as a geometry_msgs/PointMessage ROS message.
How can i get only the center coordinates of a detected object?

**Comment by cagbal** [comment]
x,y in world coordinates or image coordinates?

**Comment by sohartma** [comment]
> 
> 
> x,y in world coordinates or image coordinates?

image coordinates. basically i need the horizontal position of the detected object

**Comment by cagbal** [comment]
Please refer to this file which is responsible of embedding bounding box info to the message format. 
https://github.com/cagbal/ros_people_object_detection_tensorflow/blob/master/src/cob_people_object_detection_tensorflow/utils.py

You will see in that file that the bounding box info is embedded with the code below. So, what you need is just to capture this by listening to the output of the detector. 

detection.mask.roi.x = int((im.width-1) * bb[1])
detection.mask.roi.y = int((im.height-1) * bb[0])
detection.mask.roi.width = int((im.width-1) * (bb[3]-bb[1]))
detection.mask.roi.height = int((im.height-1) * (bb[2]-bb[0]))

**Comment by sohartma** [comment]
Thanks! I already did that and it gives me all the data.
So i can just create a point message (http://docs.ros.org/melodic/api/geometry_msgs/html/msg/Point.html) with detection.mask.roi.x and detection.mask.roi.y in the utils.py file?

**Comment by cagbal** [comment]
You can either:
     1. Create a new function in utils.py and use it to create the message. Of course, you need to change message type also in publisher. 
     or 
     2. You may leave the main code untouched and create a new converter node that is subscribing to the output of the detector and emits the Point msg.

**Comment by sohartma** [comment]
Ok! I will try! thank you

**Comment by cagbal** [comment]
No problem. I am closing the issue.
