### ISSUE TITLE
Performance issue in the definition of testResizeToRangeWithDynamicSpatialShape, src/object_detection/core/preprocessor_test.py(P1)

### ISSUE THREAD

**Issue by DLPerf** [cagbal/cob_people_object_detection_tensorflow#53]
Hello, I found a performance issue in the definition of `testResizeToRangeWithDynamicSpatialShape`, src/object_detection/core/preprocessor_test.py, [`tf.shape(out_image)`](https://github.com/cagbal/ros_people_object_detection_tensorflow/blob/982ffd4a54b8059638f5cd4aa167299c7fc9e61f/src/object_detection/core/preprocessor_test.py#L2234) will created repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by cagbal** [comment]
Hi. Sorry for my very late reply. Thank you for your interest. The problem is that this repo becomes a little old at the moment. There are issues with Python libraries. If you create a PR, I would appreciate it. Apart from it, the repo needs a major update :)
